---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: keystore-secret-bootstrap
type: Opaque
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: keystore-secret-bootstrap-es
  namespace: manufacturing-dev
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: keystore-secret-bootstrap-prova
    template:
      type: Opaque
    data:
      password: {{ "{{ keystore-password }}" }}
  data:
  - secretKey: keystore-password
    remoteRef:
      key: secret/data/hub/plant-manager-certificate
      property: password
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bootstrap
spec:
  commonName: plant-manager-service.manufacturing-dev.qiot-project.io
  dnsNames:
  - plant-manager-service.manufacturing-dev.qiot-project.io
  - plant-manager-service.manufacturing-dev.svc
  issuerRef:
    name: ocp-install-issuer-vault
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: keystore-secret-bootstrap
  secretName: bootstrap-certificate
