apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: postgresql-es
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: postgresql
    template:
      type: Opaque
      data:
        POSTGRESQL_DATABASE: {{ .Values.postgresql.POSTGRESQL_DATABASE }}
        POSTGRESQL_USER: {{ .Values.postgresql.POSTGRESQL_USER }}
        POSTGRESQL_PASSWORD: "{{ "{{ .postgresql_password | toString }}" }}"
  data:
  - secretKey: postgresql_password
    remoteRef:
      key: {{ .Values.postgresql.vault_keypath }}
      property: postgresql_password
