apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: mongodb-es
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: mongodb
    template:
      type: Opaque
      data:
        MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.MONGO_INITDB_ROOT_USERNAME }}
        MONGODB_USER: {{ .Values.mongo.MONGODB_USER }}
        MONGODB_DATABASE: {{ .Values.mongo.MONGODB_DATABASE }}
        MONGO_INITDB_ROOT_PASSWORD: "{{ "{{ .mongo_initdb_root_password | toString }}" }}"
        MONGODB_ADMIN_PASSWORD: "{{ "{{ .mongodb_admin_password | toString }}" }}"
        MONGODB_PASSWORD: "{{ "{{ .mongodb_password | toString }}" }}"
  data:
  - secretKey: mongo_initdb_root_password
    remoteRef:
      key: {{ .Values.mongo.vault_keypath }}
      property: mongo_initdb_root_password
  - secretKey: mongodb_admin_password
    remoteRef:
      key: {{ .Values.mongo.vault_keypath }}
      property: mongodb_admin_password
  - secretKey: mongodb_password
    remoteRef:
      key: {{ .Values.mongo.vault_keypath }}
      property: mongodb_password
