{{- $sa := (lookup "v1" "ServiceAccount" .Release.Namespace "default" ) -}}
# Force a token for the vault user so we can use its name in the vault issuer template
---
apiVersion: v1
kind: Secret
metadata:
  name: registration-service-secret
  annotations:
    kubernetes.io/service-account.name: registration-service
type: kubernetes.io/service-account-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "issuer.fullname" . }}-vault
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
spec:
  vault:
    path: {{ .Release.Namespace }}-pki/sign/{{ .Values.baseDomain }} 
    server: {{ .Values.issuer.vault.server }}
    caBundleSecretRef:
      name: openshift-service-ca.crt
      key: caBundle
    auth:
      kubernetes:
        role: {{ .Release.Namespace }}-{{ .Values.baseDomain }}
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: registration-service-secret
          key: token
