{{- $sa := (lookup "v1" "ServiceAccount" .Release.Namespace "default" ) -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "issuer.fullname" . }}-vault
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
spec:
  vault:
    path: {{ .Release.Namespace }}-pki/sign/{{ .Values.baseDomain }} 
    server: {{ .Values.issuer.vault.server }}
    caBundleSecretRef:
      name: openshift-service-ca.crt
      key: caBundle
    auth:
      kubernetes:
        role: {{ .Release.Namespace }}-{{ .Values.baseDomain }}
        mountPath: /v1/auth/kubernetes
        secretRef:
          key: token
          {{- range $sa.secrets }}
          {{- if contains  "token" .name }}
          name: {{ .name }}
          {{- end -}}
          {{- end }}
