apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "issuer.fullname" . }}-wait-for-secret
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: 
      restartPolicy: Never
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.oc.image.repository }}:{{ .Values.oc.image.tag }}
        command:
        - /bin/bash
        - -c
        - |
          oc wait --for=condition=Available=true secret/openshift-service-ca.crt -n {{ .Values.issuer.vault.namespace }} --timeout=900s
        name: wait-for-openshift-service-ca-secret
      dnsPolicy: ClusterFirst
