apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "issuer.fullname" . }}-wait-for-secret
  labels:
    {{- include "issuer.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      serviceAccountName: registration-service
      restartPolicy: Never
      terminationGracePeriodSeconds: 60
      containers:
      - image: {{ .Values.oc.image.repository }}:{{ .Values.oc.image.tag }}
        command:
        - /bin/bash
        - -c
        - |
          while ! kubectl get secret openshift-service-ca.crt --namespace {{ .Release.Namespace }}; do
            echo "Waiting for my secret. CTRL-C to exit."; sleep 1
          done
        name: wait-for-openshift-service-ca-secret
      dnsPolicy: ClusterFirst
