# This playbook fetches the service-ca.crt from a config map and copies it into a
# secret. Reason for this is that the cert-manager issuer only supports CASecretRef and not
# CAConfigMapRef
---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ns: manufacturing-dev
  tasks:
    - name: Find openshift-service-ca.crt configmap
      kubernetes.core.k8s_info:
        kind: ConfigMap
        api_version: "v1"
        name: openshift-service-ca.crt
        namespace: "{{ ns }}"
      register: ocp_service_ca

    - name: Set CABundle fact
      ansible.builtin.set_fact:
        ca_bundle: "{{ ocp_service_ca['resources'][0]['data']['service-ca.crt'] }}"

    - name: Create secret in the manufacturing-dev NS
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: "openshift-service-ca.crt"
            namespace: "{{ ns }}"
          data:
            caBundle: "{{ ca_bundle | b64encode }}"
          type: Opaque
